name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: false
   
    - name: Install all dependencies
      run: npm run install:all
      env:
        CI: true

    - name: Make Jest executable
      run: chmod +x backend/node_modules/.bin/jest

    - name: Verify Jest
      run: cd backend && npx jest --version


    - name: Run backend tests
      run: cd backend && npm run test:ci
    
    - name: Run frontend tests  
      run: cd frontend && npm run test:ci
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        file: ./frontend/coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        token: ${{ secrets.CODECOV_TOKEN }}
    
    - name: Build application
      run: npm run build
    
    - name: Install Playwright browsers
      run: cd frontend && npx playwright install chromium
    
    - name: Start backend server
      run: |
        cd backend && npm start &
        sleep 10
      
    - name: Run E2E tests
      run: cd frontend && npm run test:e2e || true
    
    - name: Upload E2E test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: e2e-test-results-${{ matrix.node-version }}
        path: |
          frontend/test-results/
          frontend/playwright-report/
          frontend/*.html
        retention-days: 30

  security-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm run install:all
    
    - name: Run security audit
      run: |
        cd frontend && npm audit --audit-level moderate || true
        cd ../backend && npm audit --audit-level moderate || true

  build-and-deploy:
    needs: [test, security-scan]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm run install:all
    
    - name: Build for production
      run: npm run build
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/build